version: "3"
services:
   nginx:
     build: ./nginx
     image: "test-django-nginx:latest"
     links:
       - app
       - pgadmin
     depends_on:
       - app
       - pgadmin
     ports:
       - "443:443"
       - "80:80"
   app:
     build: .
     image: "test-django:latest"
     deploy:
       replicas: 2
     links:
       - "postgresql"
     depends_on:
       - "postgresql"
#     ports:
#       - "8000:8000"
#     expose:
#       - 8000
     environment:
       POSTGRESQL_HOST: postgresql
       POSTGRESQL_PORT: 5432
   pgadmin:
      build: .
      image: dpage/pgadmin4
      links:
        - "postgresql"
      depends_on:
        - "postgresql"
#      ports:
#        - "80:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: silverlight@gmail.com
        PGADMIN_DEFAULT_PASSWORD: k1h2o3a4i5
   postgresql:
      image: "silverlight-postgre:11"
      restart: always
      volumes:
        - /var/lib/postgresql/data/test_django:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: test_django
        POSTGRES_DB: django_test
        POSTRES_PASSWORD: k1h2o3a4i5

   nginx_dashboard:
      build: ./nginx_dashboard
      image: "test-django-nginx-dashboard:latest"
      restart: unless-stopped
      ports:
        - 5050:5050
        - 3000:3000
      links:
        - grafana
      depends_on:
        - grafana

   prometheus:
      build: ./docker_prometheus
      image: "test-django-prometheus:latest"
      restart: unless-stopped
      command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - "--web.console.templates=/usr/share/prometheus/consoles"
#      - '--alertmanager.url=http://alertmanager:9093'
#      ports:
#        - 9090:9090
      links:
        - cadvisor:cadvisor
        - node-exporter:node-exporter
        - nginx:nginx
      depends_on:
        - cadvisor
        - node-exporter
        - nginx

   node-exporter:
      image: prom/node-exporter:latest
      restart: unless-stopped
#      expose:
#        - 9100
#      ports:
#        - 9100:9100

   cadvisor:
      image: google/cadvisor:latest
      restart: unless-stopped
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
      command: --docker_only=true
#      expose:
#        - 8080
#      ports:
#        - 8080:8080

   grafana:
      build: ./docker_grafana
      image: "test-django-grafana:latest"
      restart: unless-stopped
      links:
        - prometheus:prometheus
      depends_on:
        - prometheus
      volumes:
        - /home/silverlight/Projects/test_django/grafana:/var/lib/grafana
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=admin
        - GF_USERS_ALLOW_SIGN_UP=false
        - GF_SERVER_DOMAIN=myrul.com
        - GF_SMTP_ENABLED=true
        - GF_SMTP_HOST=smtp.gmail.com:587
        - GF_SMTP_USER=myadrress@gmail.com
        - GF_SMTP_PASSWORD=mypassword
        - GF_SMTP_FROM_ADDRESS=myaddress@gmail.com
#      ports:
#        - 3000:3000
      user: "root"

